[project]
name = "nonebot-plugin-callapi"
version = "0.1.3.post1"
description = "Use bot command to call its API"
authors = [{ name = "student_2333", email = "lgc2333@126.com" }]
dependencies = [
    "nonebot2>=2.0.0",
    "nonebot-adapter-onebot>=2.2.0",
    "pydantic>=1.10.4",
    "Pygments>=2.15.1",
    "pil-utils>=0.1.7",
    "nonebot-plugin-send-anything-anywhere>=0.2.5",
]
requires-python = ">=3.8,<4.0"
readme = "README.md"
license = { text = "MIT" }

[project.urls]
homepage = "https://github.com/lgc-NB2Dev/nonebot-plugin-callapi"

[tool.pdm.build]
includes = []

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
